### ISSUE TITLE
Error Finding index.js file

### ISSUE THREAD

**Issue by CUCraigT** [southworkscom/SOUTHWORKS-azure-pipelines-tasks#24]
I am trying to use this to publish a comment back to my GitHub PR from a text file. I have a simple test3.txt file in my messages/ directory in my project in GitHub. When I try to run the module, I get the following error:

`File not found: '/home/vsts/work/_tasks/github-pr-comment_f5fbab81-da68-4a17-883f-3d2d6368b216/0.1.0/index.js`

Here is my config in my DevOps pipeline:

```
- task: github-pr-comment@0
  inputs:
    userToken: '[removed for security]'
    repository: '$(Build.Repository.Name)'
    prNumber: '$(System.PullRequest.PullRequestNumber)'
    bodyFilePath: 'messages/'
    extension: 'txt'
```
